cd.c: Error!
Error: NEWLINE_PRECEDES_FUNC (line:  27, col:   1):	Functions must be separated by a newline
error_handling.c: Error!
Error: TOO_MANY_LINES       (line:  43, col:   1):	Function has more than 25 lines
Error: NEWLINE_PRECEDES_FUNC (line:  44, col:   1):	Functions must be separated by a newline
free.c: Error!
Error: WRONG_SCOPE_COMMENT  (line:  60, col:  21):	Comment is invalid in this scope
Error: WRONG_SCOPE_COMMENT  (line:  60, col:  21):	Comment is invalid in this scope
Error: WRONG_SCOPE_COMMENT  (line:  62, col:  17):	Comment is invalid in this scope
Error: WRONG_SCOPE_COMMENT  (line:  62, col:  17):	Comment is invalid in this scope
header.h: Error!
Error: USER_DEFINED_TYPEDEF (line:  62, col:  25):	User defined typedef must start with t_
Error: USER_DEFINED_TYPEDEF (line:  69, col:  25):	User defined typedef must start with t_
Error: LINE_TOO_LONG        (line: 175, col:  86):	line too long
Error: LINE_TOO_LONG        (line: 177, col:  86):	line too long
Error: TOO_MANY_ARGS        (line: 288, col:  59):	Function has more than 4 arguments
heredoc_expand.c: Error!
Error: WRONG_SCOPE_COMMENT  (line:  26, col:  13):	Comment is invalid in this scope
Error: TOO_MANY_LINES       (line:  48, col:   1):	Function has more than 25 lines
Error: NEWLINE_PRECEDES_FUNC (line:  49, col:   1):	Functions must be separated by a newline
Error: NEWLINE_PRECEDES_FUNC (line:  65, col:   1):	Functions must be separated by a newline
Error: NEWLINE_PRECEDES_FUNC (line:  93, col:   1):	Functions must be separated by a newline
Error: NEWLINE_PRECEDES_FUNC (line: 108, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_ARGS        (line: 109, col:  27):	Function has more than 4 arguments
Error: TOO_MANY_LINES       (line: 141, col:   1):	Function has more than 25 lines
Error: NEWLINE_PRECEDES_FUNC (line: 142, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 142, col:   1):	Too many functions in file
Error: NEWLINE_PRECEDES_FUNC (line: 157, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 157, col:   1):	Too many functions in file
Error: NEWLINE_PRECEDES_FUNC (line: 170, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 170, col:   1):	Too many functions in file
Error: TOO_MANY_FUNCS       (line: 190, col:   1):	Too many functions in file
Error: TOO_MANY_LINES       (line: 230, col:   1):	Function has more than 25 lines
input_error_handling.c: Error!
Error: TOO_MANY_LINES       (line:  61, col:   1):	Function has more than 25 lines
Error: NEWLINE_PRECEDES_FUNC (line:  62, col:   1):	Functions must be separated by a newline
Error: NEWLINE_PRECEDES_FUNC (line:  88, col:   1):	Functions must be separated by a newline
Error: NEWLINE_PRECEDES_FUNC (line: 110, col:   1):	Functions must be separated by a newline
Error: NEWLINE_PRECEDES_FUNC (line: 123, col:   1):	Functions must be separated by a newline
Error: NEWLINE_PRECEDES_FUNC (line: 138, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 138, col:   1):	Too many functions in file
Error: LINE_TOO_LONG        (line: 149, col:  83):	line too long
Error: NEWLINE_PRECEDES_FUNC (line: 161, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 161, col:   1):	Too many functions in file
Error: LINE_TOO_LONG        (line: 170, col:  83):	line too long
Error: NEWLINE_PRECEDES_FUNC (line: 189, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 189, col:   1):	Too many functions in file
Error: LINE_TOO_LONG        (line: 198, col:  83):	line too long
Error: TOO_MANY_LINES       (line: 217, col:   1):	Function has more than 25 lines
Error: NEWLINE_PRECEDES_FUNC (line: 218, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 218, col:   1):	Too many functions in file
Error: NEWLINE_PRECEDES_FUNC (line: 242, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 242, col:   1):	Too many functions in file
Error: LINE_TOO_LONG        (line: 251, col:  83):	line too long
Error: NEWLINE_PRECEDES_FUNC (line: 260, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 260, col:   1):	Too many functions in file
Error: TOO_MANY_FUNCS       (line: 283, col:   1):	Too many functions in file
Error: NEWLINE_PRECEDES_FUNC (line: 310, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 310, col:   1):	Too many functions in file
Error: NEWLINE_PRECEDES_FUNC (line: 328, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 328, col:   1):	Too many functions in file
Error: NEWLINE_PRECEDES_FUNC (line: 334, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 334, col:   1):	Too many functions in file
Error: BRACE_SHOULD_EOL     (line: 353, col:   1):	Expected newline after brace
main.c: Error!
Error: TOO_MANY_LINES       (line:  69, col:   1):	Function has more than 25 lines
Error: NEWLINE_PRECEDES_FUNC (line:  91, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 100, col:   1):	Too many functions in file
Error: NEWLINE_PRECEDES_FUNC (line: 115, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 115, col:   1):	Too many functions in file
Error: TOO_MANY_LINES       (line: 149, col:   1):	Function has more than 25 lines
Error: TOO_MANY_FUNCS       (line: 151, col:   1):	Too many functions in file
Error: TOO_MANY_FUNCS       (line: 163, col:   1):	Too many functions in file
Error: NEWLINE_PRECEDES_FUNC (line: 178, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 178, col:   1):	Too many functions in file
Error: TOO_MANY_FUNCS       (line: 206, col:   1):	Too many functions in file
Error: TOO_MANY_FUNCS       (line: 227, col:   1):	Too many functions in file
Error: NEWLINE_PRECEDES_FUNC (line: 247, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 247, col:   1):	Too many functions in file
Error: NEWLINE_PRECEDES_FUNC (line: 262, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 262, col:   1):	Too many functions in file
Error: NEWLINE_PRECEDES_FUNC (line: 273, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 273, col:   1):	Too many functions in file
Error: NEWLINE_PRECEDES_FUNC (line: 284, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 284, col:   1):	Too many functions in file
Error: TOO_MANY_FUNCS       (line: 295, col:   1):	Too many functions in file
Error: TOO_MANY_FUNCS       (line: 311, col:   1):	Too many functions in file
Error: TOO_MANY_FUNCS       (line: 334, col:   1):	Too many functions in file
Error: NEWLINE_PRECEDES_FUNC (line: 346, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 346, col:   1):	Too many functions in file
Error: TOO_MANY_FUNCS       (line: 368, col:   1):	Too many functions in file
Error: TOO_MANY_FUNCS       (line: 382, col:   1):	Too many functions in file
Error: TOO_MANY_ARGS        (line: 383, col:  27):	Function has more than 4 arguments
Error: TOO_MANY_LINES       (line: 415, col:   1):	Function has more than 25 lines
Error: NEWLINE_PRECEDES_FUNC (line: 416, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 416, col:   1):	Too many functions in file
Error: TOO_MANY_ARGS        (line: 417, col:  51):	Function has more than 4 arguments
Error: NEWLINE_PRECEDES_FUNC (line: 432, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 432, col:   1):	Too many functions in file
Error: NEWLINE_PRECEDES_FUNC (line: 445, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 445, col:   1):	Too many functions in file
Error: NEWLINE_PRECEDES_FUNC (line: 463, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 463, col:   1):	Too many functions in file
Error: NEWLINE_PRECEDES_FUNC (line: 487, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 487, col:   1):	Too many functions in file
Error: TOO_MANY_LINES       (line: 519, col:   1):	Function has more than 25 lines
Error: TOO_MANY_FUNCS       (line: 521, col:   1):	Too many functions in file
quotes.c: OK!
signals.c: OK!
token_split.c: Error!
Error: TOO_FEW_TAB          (line:  38, col:  13):	Missing tabs for indent level
Error: NEWLINE_PRECEDES_FUNC (line:  42, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line:  76, col:   1):	Too many functions in file
Error: TOO_MANY_FUNCS       (line:  92, col:   1):	Too many functions in file
Error: TOO_MANY_FUNCS       (line: 118, col:   1):	Too many functions in file
Error: TOO_MANY_FUNCS       (line: 146, col:   1):	Too many functions in file
Error: TOO_MANY_FUNCS       (line: 164, col:   1):	Too many functions in file
Error: TOO_MANY_FUNCS       (line: 173, col:   1):	Too many functions in file
Error: TOO_MANY_ARGS        (line: 174, col:  25):	Function has more than 4 arguments
Error: TOO_MANY_FUNCS       (line: 179, col:   1):	Too many functions in file
Error: TOO_MANY_ARGS        (line: 180, col:  25):	Function has more than 4 arguments
Error: TOO_MANY_FUNCS       (line: 195, col:   1):	Too many functions in file
Error: TOO_MANY_LINES       (line: 227, col:   1):	Function has more than 25 lines
utils_1.c: OK!
builtins/builtins.h: OK!
builtins/cd.c: Error!
Error: WRONG_SCOPE_COMMENT  (line: 101, col:   9):	Comment is invalid in this scope
Error: NEWLINE_PRECEDES_FUNC (line: 110, col:   1):	Functions must be separated by a newline
Error: WRONG_SCOPE_COMMENT  (line: 125, col:   9):	Comment is invalid in this scope
Error: WRONG_SCOPE_COMMENT  (line: 126, col:   9):	Comment is invalid in this scope
Error: WRONG_SCOPE_COMMENT  (line: 127, col:   9):	Comment is invalid in this scope
Error: WRONG_SCOPE_COMMENT  (line: 128, col:   9):	Comment is invalid in this scope
Error: TOO_MANY_LINES       (line: 141, col:   1):	Function has more than 25 lines
Error: NEWLINE_PRECEDES_FUNC (line: 142, col:   1):	Functions must be separated by a newline
Error: NEWLINE_PRECEDES_FUNC (line: 160, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_FUNCS       (line: 160, col:   1):	Too many functions in file
Error: WRONG_SCOPE_COMMENT  (line: 181, col:  13):	Comment is invalid in this scope
Error: WRONG_SCOPE_COMMENT  (line: 182, col:  13):	Comment is invalid in this scope
Error: WRONG_SCOPE_COMMENT  (line: 183, col:  13):	Comment is invalid in this scope
Error: TOO_MANY_LINES       (line: 193, col:   1):	Function has more than 25 lines
Error: TOO_MANY_FUNCS       (line: 195, col:   1):	Too many functions in file
Error: TOO_MANY_FUNCS       (line: 216, col:   1):	Too many functions in file
builtins/cd_helper.c: OK!
builtins/export.c: OK!
builtins/export_helper.c: OK!
builtins/main_export.c: OK!
builtins/echo.c: OK!
builtins/env.c: OK!
builtins/env_helper.c: OK!
builtins/echo_helper.c: OK!
builtins/unset.c: OK!
builtins/exit.c: Error!
Error: TERNARY_FBIDDEN      (line:  53, col:  31):	Ternaries are forbidden
builtins/main_exit.c: OK!
builtins/pwd.c: OK!
dups/dups.c: Error!
Error: LINE_TOO_LONG        (line:  24, col:   1):	line too long
Error: LINE_TOO_LONG        (line:  24, col:  86):	line too long
Error: NEWLINE_PRECEDES_FUNC (line:  25, col:   1):	Functions must be separated by a newline
Error: SPC_AFTER_OPERATOR   (line:  26, col:  23):	missing space after operator
Error: SPC_AFTER_PAR        (line:  41, col:  18):	Missing space after parenthesis (brace/bracket)
Error: WRONG_SCOPE_COMMENT  (line:  41, col:  19):	Comment is invalid in this scope
Error: WRONG_SCOPE_COMMENT  (line:  41, col:  19):	Comment is invalid in this scope
Error: EMPTY_LINE_FUNCTION  (line:  52, col:   1):	Empty line in function
dups/dups.h: Error!
Error: NL_AFTER_PREPROC     (line:  17, col:   1):	Preprocessor statement must be followed by a newline
Error: LINE_TOO_LONG        (line:  29, col:  90):	line too long
Error: LINE_TOO_LONG        (line:  31, col:  90):	line too long
Error: LINE_TOO_LONG        (line:  33, col:  83):	line too long
Error: LINE_TOO_LONG        (line:  35, col:  84):	line too long
Error: SPC_AFTER_OPERATOR   (line:  41, col:  59):	missing space after operator
dups/dups_helper.c: Error!
Error: CONSECUTIVE_NEWLINES (line:  16, col:   1):	Consecutive newlines
Error: CONSECUTIVE_NEWLINES (line:  17, col:   1):	Consecutive newlines
Error: LINE_TOO_LONG        (line:  20, col:  90):	line too long
dups/dups_helper1.c: Error!
Error: NEWLINE_PRECEDES_FUNC (line:  45, col:   1):	Functions must be separated by a newline
Error: WRONG_SCOPE_COMMENT  (line:  68, col:   5):	Comment is invalid in this scope
Error: WRONG_SCOPE_COMMENT  (line:  86, col:  13):	Comment is invalid in this scope
Error: WRONG_SCOPE_COMMENT  (line:  87, col:  13):	Comment is invalid in this scope
Error: WRONG_SCOPE_COMMENT  (line:  88, col:  13):	Comment is invalid in this scope
Error: WRONG_SCOPE_COMMENT  (line:  89, col:  13):	Comment is invalid in this scope
Error: TOO_MANY_LINES       (line:  93, col:   1):	Function has more than 25 lines
Error: SPACE_REPLACE_TAB    (line:  97, col:   8):	Found space when expecting tab
execution/execution.h: Error!
Error: NL_AFTER_PREPROC     (line:  17, col:   1):	Preprocessor statement must be followed by a newline
Error: LINE_TOO_LONG        (line:  31, col:  82):	line too long
execution/execution1.c: Error!
Error: WRONG_SCOPE_COMMENT  (line:  70, col:   9):	Comment is invalid in this scope
Error: WRONG_SCOPE_COMMENT  (line:  71, col:   9):	Comment is invalid in this scope
Error: WRONG_SCOPE_COMMENT  (line:  72, col:   9):	Comment is invalid in this scope
Error: WRONG_SCOPE_COMMENT  (line:  73, col:   9):	Comment is invalid in this scope
Error: WRONG_SCOPE_COMMENT  (line:  74, col:   9):	Comment is invalid in this scope
Error: TOO_MANY_LINES       (line: 128, col:   1):	Function has more than 25 lines
execution/execution2.c: Error!
Error: BRACE_SHOULD_EOL     (line:  57, col:   1):	Expected newline after brace
expand_dollar/dollar.c: Error!
Error: NEWLINE_PRECEDES_FUNC (line:  43, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_LINES       (line:  72, col:   1):	Function has more than 25 lines
Error: LINE_TOO_LONG        (line:  73, col:   1):	line too long
Error: LINE_TOO_LONG        (line:  73, col:   1):	line too long
Error: LINE_TOO_LONG        (line:  73, col:   1):	line too long
Error: NEWLINE_PRECEDES_FUNC (line:  89, col:   1):	Functions must be separated by a newline
Error: NEWLINE_PRECEDES_FUNC (line: 117, col:   1):	Functions must be separated by a newline
Error: NEWLINE_PRECEDES_FUNC (line: 126, col:   1):	Functions must be separated by a newline
Error: TOO_MANY_TAB         (line: 136, col:  13):	Extra tabs for indent level
expand_dollar/dollar.h: Error!
Error: NL_AFTER_PREPROC     (line:  17, col:   1):	Preprocessor statement must be followed by a newline
expand_dollar/dollar1.c: Error!
Error: WRONG_SCOPE_COMMENT  (line:  21, col:   5):	Comment is invalid in this scope
Error: NEWLINE_PRECEDES_FUNC (line:  26, col:   1):	Functions must be separated by a newline
Error: NEWLINE_PRECEDES_FUNC (line:  56, col:   1):	Functions must be separated by a newline
expand_dollar/dollar2.c: Error!
Error: NEWLINE_PRECEDES_FUNC (line:  28, col:   1):	Functions must be separated by a newline
Error: NEWLINE_PRECEDES_FUNC (line:  41, col:   1):	Functions must be separated by a newline
Error: NEWLINE_PRECEDES_FUNC (line:  50, col:   1):	Functions must be separated by a newline
Error: SPACE_REPLACE_TAB    (line:  52, col:   8):	Found space when expecting tab
Error: SPACE_AFTER_KW       (line:  57, col:   9):	Missing space after keyword
Error: SPC_BFR_PAR          (line:  57, col:  11):	Missing space before parenthesis (brace/bracket)
Error: BRACE_SHOULD_EOL     (line:  61, col:   1):	Expected newline after brace
libft/ft_isdigit.c: OK!
libft/ft_itoa.c: OK!
libft/ft_putendl_fd.c: OK!
libft/ft_split.c: OK!
libft/ft_strchr.c: OK!
libft/ft_strdup.c: OK!
libft/ft_strjoin.c: OK!
libft/ft_strlen.c: OK!
libft/ft_strnstr.c: OK!
libft/libft.h: OK!
tokenization/updated_tokenization.c: OK!
tokenization/tokenization.c: OK!
tokenization/tokenization.h: OK!
tokenization/token_type.c: OK!
tokenization/main_tokenization.c: OK!
tokenization/delimeter_check.c: OK!
tokenization/tokenization_helper.c: OK!
